### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by Swoogan** [craibuc/PsTokens#1]
The readme doesn't say what the token format is. Also, the example seems to be invalid syntax:

```
Merge-Tokens -tokens @{FirstName: 'foo'; LastName: 'bar'}
```

I think it should be:

```
Merge-Tokens -tokens @{'FirstName' = 'foo'; 'LastName' = 'bar'}
```

**Comment by craibuc** [comment]
Good catch.  Readme has been corrected.
